# Generated by Django 3.0.3 on 2020-03-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Puzzle',
            fields=[
                ('puzzleID', models.AutoField(primary_key=True, serialize=False)),
                ('puzzleType', models.CharField(blank=True, choices=[('2', '2x2'), ('3', '3x3'), ('4', '4x4'), ('5', '5x5')], max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
        migrations.RemoveField(
            model_name='scramble',
            name='scrambleLength',
        ),
        migrations.AlterModelTable(
            name='scramble',
            table=None,
        ),
        migrations.AddField(
            model_name='scramble',
            name='scrambleType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Puzzle'),
        ),
    ]
