# Generated by Django 3.0.3 on 2020-03-03 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scramble',
            fields=[
                ('scrambleID', models.AutoField(primary_key=True, serialize=False)),
                ('scrambleLength', models.IntegerField()),
                ('scramble', models.CharField(blank=True, max_length=45)),
            ],
            options={
                'db_table': 'scramble',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('userEmail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='myapp.User')),
                ('adminEmail', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puzzleType', models.CharField(choices=[('2', '2x2'), ('3', '3x3'), ('4', '4x4'), ('5', '5x5')], max_length=10)),
                ('best', models.BigIntegerField(blank=True)),
                ('average', models.BigIntegerField(blank=True)),
                ('worst', models.BigIntegerField(blank=True)),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
            options={
                'db_table': 'statistic',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postName', models.CharField(blank=True, max_length=20)),
                ('postDate', models.DateTimeField()),
                ('userID', models.ForeignKey(db_column='userID', on_delete=django.db.models.deletion.CASCADE, to='myapp.User')),
            ],
            options={
                'db_table': 'blogpost',
            },
        ),
    ]
